openapi: 3.0.0
info:
  title: API de Apólices
  version: 1.0.0
  description: API para gerenciar apólices de seguro
servers:
  - url: http://localhost:3000
    description: Servidor local
paths:
  /apolices:
    get:
      tags:
        - Apolices
      summary: Listar apólices
      parameters:
        - name: _page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: _per_page
          in: query
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Lista de apólices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Apolice'
    post:
      tags:
        - Apolices
      summary: Criar nova apólice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Apolice'
      responses:
        '201':
          description: Apólice criada com sucesso
        '400':
          description: Já existe uma apólice para o CPF/CNPJ informado
  /apolices/{id}:
    get:
      tags:
        - Apolices
      summary: Obter apólice por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 6f7g
      responses:
        '200':
          description: Detalhes da apólice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apolice'
        '404':
          description: Apólice não encontrada
    patch:
      tags:
        - Apolices
      summary: Atualizar apólice existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 6f7g
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Apolice'
      responses:
        '200':
          description: Apólice atualizada com sucesso
        '400':
          description: Já existe uma apólice para o CPF/CNPJ informado
    delete:
      tags:
        - Apolices
      summary: Deletar apólice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 6f7g
      responses:
        '200':
          description: Apólice deletada com sucesso
        '404':
          description: Apólice não encontrada
components:
  schemas:
    Apolice:
      type: object
      required:
        - numero
        - valor_premio
        - segurado
        - coberturas
      properties:
        id:
          type: string
          example: 6f7g
        numero:
          type: integer
          example: 1006
        valor_premio:
          type: number
          format: float
          example: 55000
        segurado:
          $ref: '#/components/schemas/Segurado'
        coberturas:
          type: array
          items:
            $ref: '#/components/schemas/Cobertura'
    Segurado:
      type: object
      required:
        - nome
        - email
        - cpf_cnpj
      properties:
        nome:
          type: string
          example: Fernanda Lima
        email:
          type: string
          format: email
          example: fernanda.lima@example.com
        cpf_cnpj:
          type: string
          example: 987.654.321-00
    Cobertura:
      type: object
      required:
        - nome
        - valor
      properties:
        nome:
          type: string
          example: Avarias
        valor:
          type: number
          format: float
          example: 20000
